[functions]
  node_bundler = "esbuild"
  # se quiser que o esbuild não exija módulos opcionais do Nest:
  ignored_node_modules = [
    "class-transformer",
    "class-validator",
    "@nestjs/websockets",
    "@nestjs/websockets/socket-module",
    "@nestjs/microservices",
    "@nestjs/microservices/microservices-module"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nest/:splat"
  status = 200
