[build]
  command = "npm run build"          
  functions = "netlify/functions"

[functions]
  node_bundler = "nft"                
  included_files = ["dist/**"]

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/nest/api"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nest/api/:splat"
  status = 200